### ISSUE TITLE
quarano.de does not redirect to www.quarano.de resulting in insecure warning

### ISSUE THREAD

**Issue by DanielHabenicht** [quarano/quarano-application#91]
Navigating to https://quarano.de/

results in a "This site is insecure" Warning. Because the serving webserver show the following certificate not matching the domain: 
![image](https://user-images.githubusercontent.com/13590797/86459314-e238c680-bd26-11ea-982b-ca9b89028728.png)

Navigating to https://www.quarano.de/ works just fine. 

BTW: I am an Angular Developer, do you need any support?

**Comment by patrickotto** [comment]
Hi Daniel,

 

thanks for the hint. We are working on that..

 

 

And yes, indeed we could need support for our angular devlopment.. we are about to extend the application with further features to support the health departments even better and try to get more health departments on board.

 

 

If you like, we would have a call to discuss this matter:

 

0172 634 1221.

 

 

Thanks,

Patrick

 

 

 

 
 

Gesendet: Freitag, 03. Juli 2020 um 12:17 Uhr
Von: "DanielHabenicht" <notifications@github.com>
An: "quarano/quarano-application" <quarano-application@noreply.github.com>
Cc: "Subscribed" <subscribed@noreply.github.com>
Betreff: [quarano/quarano-application] quarano.de does not redirect to www.quarano.de resulting in insecure warning (#91)


 

Navigating to https://quarano.de/

results in a "This site is insecure" Warning. Because the serving webserver show the following certificate not matching the domain:


Navigating to https://www.quarano.de/ works just fine.

BTW: I am an Angular Developer, do you need any support?

**Comment by DanielHabenicht** [comment]
Hi Patrick, 

I am currently writing exams but I will have more time at the beginning of August. 
I will give you a call then. 

If you want, you can remove the telephone number. I have noted it.

**Comment by odrotbohm** [comment]
Seems to be fixed.

**Comment by DanielHabenicht** [comment]
@odrotbohm scheint wieder nicht mehr zu funktionieren: https://www.quarano.de/
